# Generated by Django 5.2.2 on 2025-06-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='estado',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('PUBLISHED', 'Publicado')], default='DRAFT', max_length=100),
        ),
    ]
